project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/jgutgesell/CS5805
  repo-actions: [source]
  title: "Julia Gutgesell's Machine Learning Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jgutgesell 

format:
  html:
    theme: flatly
    css: styles.css

editor: visual

